### ISSUE TITLE
px name == ux

### ISSUE THREAD

**Issue by wolfv** [Evil-Spirit/Adjacent#1]
Hey, I am almost done with the initial port. Just noting some things I found along the way:

Is this on purpose?

https://github.com/Evil-Spirit/Adjacent/blob/70f3297e2c5e2ec940c7ddb1f5de703bc3a78991/src/ExpBasis.h#L19-L21

**Comment by Evil-Spirit** [comment]
no, just copypaste, ofc must be px, py, pz (this is used for debugging mostly)

**Comment by wolfv** [comment]
good to know!
